Update fast-feedback.component.ts
fix complication error:
ERROR in src/app/fast-feedback/fast-feedback.component.ts(55,14): error TS2339: Property 'team_id' does not exist on type '{ context_id: any; }'.
src/app/fast-feedback/fast-feedback.component.ts(58,14): error TS2339: Property 'target_user_id' does not exist on type '{ context_id: any; }'.